apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-root-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/100-hours-a-week/21-iceT-gitops
    targetRevision: main
    path: argo-apps/apps-prod
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
