apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apm-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elastic/helm-charts.git
    targetRevision: main
    path: apps-prod/resources/apm-server-ingress
    helm:
      values: |
        imageTag: 8.5.1

        elasticsearchHosts: ["https://elasticsearch-master.elk.svc:9200"]

        output.elasticsearch:
          hosts: ["https://elasticsearch-master.elk.svc:9200"]
          username: "elastic"
          password: "changeme1234"
          ssl:
            enabled: true
            verification_mode: none

        apm-server:
          host: "0.0.0.0:8200"

  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

