apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    chart: aws-ebs-csi-driver
    targetRevision: "2.45.1"        # ← 여기를 실제 버전 태그로 변경
    helm:
      values: |-
        controller:
          serviceAccount:
            create: true
            name: ebs-csi-controller-sa
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::266735804784:role/AmazonEKS_EBS_CSI_Driver_IRSA
                                         # ← 여기를 실제 IRSA Role ARN으로 변경
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true       # ← Server-Side Apply 활성화
