apiVersion: argoproj.io/v1alpha1  # Argo CD Application API 버전
kind: Application                 # 리소스 종류
metadata:
  name: aws-ebs-csi-driver        # Application 이름
  namespace: argocd                # 생성 네임스페이스
spec:
  project: default                 # Argo CD 프로젝트
  source:
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver  # 차트 저장소
    chart: aws-ebs-csi-driver     # 차트 이름
    targetRevision: latest        # 최신 버전 사용
    helm:
      parameters:
        - name: controller.serviceAccount.create  # CSI 컨트롤러 서비스어카운트 생성
          value: "true"
        - name: controller.serviceAccount.name    # 서비스어카운트 이름 지정
          value: "ebs-csi-controller-sa"
        - name: controller.serviceAccount.annotations.eks\.amazonaws\.com/role-arn  # IRSA용 IAM 역할 ARN 주석
          value: "{{ .Values.ebsCsiIrsaRoleArn }}"
  destination:
    server: https://kubernetes.default.svc  # 클러스터 API 서버 주소
    namespace: kube-system               # kube-system 네임스페이스
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
