apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-stack
    targetRevision: "2.16.1"
    helm:
      values: |
        elasticsearch:
          enabled: true
          nodeSets:
            - name: default
              count: 1
              config:
                node.store.allow_mmap: false
   
        kibana:
          enabled: true
          count: 1
          elasticsearchRef:
            name: elasticsearch
          ingress:
            enabled: true
            className: alb
            annotations:
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/group.name: koco-alb-group
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
              alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:266735804784:certificate/5f2a8c3b-a576-4295-84c1-beb75ca562d9 
              alb.ingress.kubernetes.io/backend-protocol: HTTP
            hosts:
              - kibana.koco-test.click

        logstash:
          enabled: true
          count: 1
          pipeline:
            - name: main
              config: |
                input { stdin { } }
                output { stdout { } }

        filebeat:
          daemonset:
            enabled: true
          deployment:
            enabled: false  
          filebeatConfig:
            filebeat.yml: |
              filebeat.inputs:
                - type: log
                  enabled: true
                  paths:
                    - /var/log/*.log
              output.elasticsearch:
                hosts: ["http://elasticsearch-master:9200"]

        metricbeat:
          daemonset:
            enabled: true
          deployment:
            enabled: false
          metricbeatConfig:
            metricbeat.yml: |
              metricbeat.modules:
                - module: system
                  metricsets:
                    - cpu
                    - memory
                    - network
                    - filesystem
                  period: 10s
              output.elasticsearch:
                hosts: ["http://elasticsearch-master:9200"]

        apm-server:
          enabled: true
          elasticsearchRef:
            name: elasticsearch
          ingress:
            enabled: true
            className: alb
            annotations:
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/group.name: koco-alb-group
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
              alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:266735804784:certificate/5f2a8c3b-a576-4295-84c1-beb75ca562d9 
              alb.ingress.kubernetes.io/backend-protocol: HTTP
            hosts:
              - apm.koco-test.click

  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
