apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/elastic/cloud-on-k8s
    targetRevision: main
    path: deploy/eck-stack
    helm:
      values: |
        nodeSets:
          - name: default
            count: 1
            config:
              node.store.allow_mmap: false

  destination:
    server: https://kubernetes.default.svc
    namespace: eck

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
