apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elastic/helm-charts.git
    targetRevision: main
    path: elasticsearch
    helm:
      values: |
        replicas: 1
        minimumMasterNodes: 1
        esConfig:
          elasticsearch.yml: |
            node.store.allow_mmap: false
        tls:
          selfSignedCertificate:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
