apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elastic/helm-charts.git
    targetRevision: main
    path: elasticsearch        # <-- community chart의 디렉터리
    helm:
      values: |
        replicas: 1
        minimumMasterNodes: 1
        esConfig:
          elasticsearch.yml: |
            node.store.allow_mmap: false

        ## ─── persistence 설정 ─────────────────────
        persistence:
          enabled: true
          storageClass: gp2      # 클러스터에 존재하는 SC 이름
          size: 30Gi             # 필요 용량으로 조정

        ## ─── TLS self-signed 활성화 ────────────────
        tls:
          selfSignedCertificate:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
