apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: kibana
    targetRevision: 12.1.3
    helm:
      values: |
        image:
          tag: "9.0.3"
        elasticsearch:
          hosts:
            - http://elasticsearch-master:9200
        ingress:
          enabled: true
          ingressClassName: alb
          hostname: kibana.koco-test.click
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/group.name: koco-alb-group
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:266735804784:certificate/5f2a8c3b-a576-4295-84c1-beb75ca562d9
            alb.ingress.kubernetes.io/backend-protocol: HTTP
  destination:
    server: https://kubernetes.default.svc
    namespace: eck
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
