apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/elastic/helm-charts.git'
    path: kibana
    targetRevision: main
    helm:
      values: |
        imageTag: 8.5.1
        elasticsearchHosts: "https://elasticsearch-master.elk.svc:9200"
        kibanaConfig:
          kibana.yml: |
            server.publicBaseUrl: "https://kibana.koco-test.click"
            server.basePath: ""
            server.rewriteBasePath: false
            server.host: "0.0.0.0"
            elasticsearch.hosts: [ "https://elasticsearch-master.elk.svc:9200" ]
            elasticsearch.serviceAccountToken: "AAEAAWVsYXN0aWMva2tpYmFuYS10b2tlbjpzck5WRko3dVN6NmlTN1NKTXhFNWZ3"
            elasticsearch.ssl.verificationMode: none
            status.allowAnonymous: true

        ingress:
          enabled: true
          className: alb
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/group.name: koco-alb-group
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:266735804784:certificate/5f2a8c3b-a576-4295-84c1-beb75ca562d9
            alb.ingress.kubernetes.io/backend-protocol: HTTP
            alb.ingress.kubernetes.io/healthcheck-path: /status
          hosts:
            - host: kibana.koco-test.click
              paths:
                - path: /
                  pathType: Prefix
          service:
            name: kibana
            port: 5601

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
