apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/elastic/helm-charts.git'
    path: kibana
    targetRevision: main
    helm:
      values: |
        imageTag: 8.5.1
        elasticsearchHosts: "https://elasticsearch-master:9200"
        elasticsearchUsername: "elastic"
        elasticsearchPassword: "changeme1234"
        elasticsearch.ssl.verificationMode: none
  
        kibanaConfig:
          kibana.yml: |
            server.publicBaseUrl: "https://kibana.koco-test.click"
  
        ingress:
          enabled: true
          className: alb
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/group.name: koco-alb-group
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
            alb.ingress.kubernetes.io/healthcheck-path: /status
            alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:266735804784:certificate/5f2a8c3b-a576-4295-84c1-beb75ca562d9
            alb.ingress.kubernetes.io/backend-protocol: HTTP
          hosts:
            - host: kibana.koco-test.click
              paths:
                - path: /
                  pathType: Prefix
  
        extraEnvs:
          - name: xpack.encryptedSavedObjects.encryptionKey
            value: "this_is_a_secure_32_byte_key_!!!"
          - name: xpack.reporting.encryptionKey
            value: "another_32_byte_secure_key_123"
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
