apiVersion: argoproj.io/v1alpha1  # Application API
kind: Application                 # 리소스 종류
metadata:
  name: kube-prometheus-stack      # 앱 이름
  namespace: argocd                # argocd 네임스페이스
spec:
  project: default                 # Argo CD 프로젝트
  source:
    repoURL: https://prometheus-community.github.io/helm-charts  # Helm repo
    chart: kube-prometheus-stack  # 차트 이름
    targetRevision: "latest"      # 최신 버전
    directory:
      recurse: true                # 하위 디렉터리까지 모두 검색
    path: monitoring/kube-prometheus-values.yaml  # values.yaml 위치 지정
  destination:
    server: https://kubernetes.default.svc  # API 서버
    namespace: monitoring            # 모니터링 네임스페이스
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
