apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logstash
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elastic/helm-charts.git
    targetRevision: main
    path: logstash
    helm:
      values: |
        imageTag: 8.5.1
        logstashConfig:
          logstash.yml: |
            xpack.monitoring.enabled: true
        
          logstash.conf: |
            input {
              stdin {}
            }
            output {
              elasticsearch {
                hosts => ["https://elasticsearch-master.elk.svc:9200"]
                ssl => true
                ssl_certificate_verification => false
                user => "elastic"
                password => "changeme1234"
              }
            }
  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
