apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logstash
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elastic/helm-charts.git
    targetRevision: main
    path: logstash
    helm:
      values: |
        imageTag: 8.5.1
        logstashConfig:
          logstash.conf: |
            input { stdin {} }
            output { stdout {} }
  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
