apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metricbeat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elastic/helm-charts.git
    targetRevision: main
    path: metricbeat
    helm:
      values: |
        imageTag: 8.5.1
        daemonset:
          enabled: true
        deployment:
          enabled: false
        metricbeatConfig:
          metricbeat.yml: |
            metricbeat.modules:
              - module: system
                metricsets:
                  - cpu
                  - memory
                  - network
                  - filesystem
                period: 10s
            output.elasticsearch:
              hosts: ["https://elasticsearch-master.elk.svc:9200"]
              username: "elastic"
              password: "changeme1234"
              ssl:
                enabled: true
                verification_mode: none
      # 여기 추가!
      repos:
        - name: prometheus-community
          url: https://prometheus-community.github.io/helm-charts
  destination:
    server: https://kubernetes.default.svc
    namespace: elk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
