apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd             # Argo CD가 설치된 네임스페이스
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: "19.5.4"    # 원하는 차트 버전
    helm:
      values: |-
        auth:
          enabled: false               # 패스워드 없이 운영
        architecture: standalone       # 단일 인스턴스 모드
        persistence:
          enabled: true                # PVC 사용
          size: 5Gi                    # 디스크 크기
          storageClass: gp2            # PVC용 스토리지 클래스
        global:
          storageClass: gp2            # 전체 차트에서 사용할 기본 스토리지 클래스
        networkPolicy:
          enabled: false               # 네트워크 폴리시 비활성화
        service:
          port: 6379                   # Redis 서비스 포트

  destination:
    server: https://kubernetes.default.svc
    namespace: redis                  # Redis를 배포할 네임스페이스
  syncPolicy:
    automated:
      prune: true      # 매니페스트에서 제거된 리소스 자동 삭제
      selfHeal: true   # 리소스 드리프트 자동 복원
    syncOptions:
      - CreateNamespace=true  # 네임스페이스가 없으면 애플리케이션 동기화 시 생성
